# Generated by Django 4.2 on 2023-07-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='项目名')),
                ('desc', models.TextField(verbose_name='项目使用描述')),
            ],
            options={
                'verbose_name': '项目表',
                'db_table': 'projects',
            },
        ),
    ]
