# Generated by Django 4.2 on 2023-07-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='desc',
            field=models.TextField(max_length=150, null=True, verbose_name='项目使用描述'),
        ),
    ]
