# Generated by Django 4.2 on 2023-08-04 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectmodel_create_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectHostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, null=True, verbose_name='创建人')),
                ('update_user', models.IntegerField(default=0, null=True, verbose_name='更新人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('real_ip', models.CharField(max_length=40, verbose_name='物理IP')),
                ('virtual_ip', models.CharField(max_length=40, verbose_name='虚拟IP')),
                ('tag', models.CharField(max_length=20, null=True, verbose_name='当前负载运行的镜像tag')),
                ('status', models.IntegerField(choices=[(0, '未启用'), (1, '已启用'), (2, '已删除')], default=0, help_text='负载状态：0-未启用，1-已启用，2-已删除', verbose_name='负载状态：0-未启用，1-已启用，2-已删除')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectmodel')),
            ],
            options={
                'verbose_name': '项目负载IP',
                'db_table': 'hosts',
            },
        ),
    ]
