version: 0.1

log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
    delete:
      enable: true
  filesystem:
    rootdirectory: /var/lib/registry
  
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3

# auth:
#   htpasswd:
#     realm: basic-realm
#     path: /auth/htpasswd


notifications:
  endpoints:
    - name: registry-test
      disabled: false
      url: 'http://192.168.1.30:8000/docker/registry/notify-url'
      # headers:
      #   X-Token: ['']
      timeout: 10s
      threshold: 10
      backoff: 1s
      ignoredmediatypes:
        - application/octet-stream
      ignore:
        mediatypes:
           - application/octet-stream
        actions:
           - pull