# 部署graylog

version: '3'

services:

  mongo:
    image: mongo:4.2
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    restart: always
    ports:
      - 27017:27017
    networks:
      - graylog

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: es
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms512m -Xmx512m"

    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - graylog

  graylog:
    image: graylog/graylog:4.2
    container_name: graylog
    volumes:
      - graylog_journal:/usr/share/graylog/data/journal
    environment:
      # 时间
      - GRAYLOG_ROOT_TIMEZONE=Asia/Shanghai
      # 16字符
      - GRAYLOG_PASSWORD_SECRET=tianjigaodaoyuan
      # echo -n "Enter Password: " && head -1 </dev/stdin | tr -d '\n' | sha256sum | cut -d" " -f1
      - GRAYLOG_ROOT_PASSWORD_SHA2=157f69a391ae15eac0d462b50ad789fd61064fcd1b15818ee4e3a02b68d92dab
      # graylog 请求地址
      - GRAYLOG_HTTP_EXTERNAL_URI=http://192.168.1.13:9009/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    networks:
      - graylog
    restart: always
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9009:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp


networks:
  graylog:
    driver: bridge

volumes:

  mongo_data:
    driver: local
    driver_opts:
      type: 'none'
      device: '/home/mydata/mongo/data'
      o: 'bind'
  es_data:
    driver: local
    driver_opts:
      type: 'none'
      device: '/home/mydata/es/data'
      o: 'bind'
  graylog_journal:
    driver: local
    driver_opts:
      type: 'none'
      device: '/home/mydata/graylog/data'
      o: 'bind'