# 服务器批量部署
# 默认拉取 latest
# 等做了部署工具后，这个文件就不能在使用
# ssh 登录服务器，执行 docker-compose -f docker-compose-test.yml up -d
# 启动单个service 执行 docker-compose -f docker-compose-test.yml up mall-product -d

version: '3'
services:

  nginx:
    image: nginx
    restart: always
    privileged: true
    container_name: nginx
    ports:
      - 8080:80
      - 8443:443

    volumes:

      # 先创建一个容器，将其中的重要文件目录复制出来，再挂在数据卷
      # docker run --name nginx -p 9001:80 -d nginx
      # docker cp nginx:/etc/nginx/nginx.conf /home/nginx/conf/nginx.conf
      # docker cp nginx:/etc/nginx/conf.d /home/nginx/conf/conf.d
      # docker cp nginx:/usr/share/nginx/html /home/nginx/

      - /home/mydata/nginx/html:/usr/share/nginx/html
      - /home/mydata/nginx/www:/var/www
      - /home/mydata/nginx/logs:/var/log/nginx
      - /home/mydata/nginx/nginx.conf/:/etc/nginx/nginx.conf
      - /home/mydata/nginx/cert:/etc/nginx/cert
      - /home/mydata/nginx/conf.d:/etc/nginx/conf.d

    environment:
      - NGINX_PORT=80
      - TZ=Asia/Shanghai


  registry:
    image: registry
    restart: always
    privileged: true
    container_name: registry
    ports:
      - 5001:5000
    environment:
      - REGISTRY_AUTH=htpasswd
      #相对于数据卷auth的路径，不要写宿主机全路径
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - /home/mydata/registry/config.yml:/etc/docker/registry/config.yml
      - /home/mydata/registry/auth:/auth
      - /home/mydata/registry/data:/var/lib/registry

  nacos:
    restart: always
    image: nacos/nacos-server
    container_name: nacos
    ports:
      - 8848:8848
      - 9848:9848
      - 9849:9849

    privileged: true
    environment:
      NACOS_AUTH_ENABLE: "true"
      NACOS_AUTH_TOKEN_EXPIRE_SECONDS: 18000
      NACOS_AUTH_TOKEN: xzd123xzd456xzd789xzd123xzd456xzd789xzd123xzd456xzd789
      NACOS_AUTH_IDENTITY_KEY: tianji
      NACOS_AUTH_IDENTITY_VALUE: tianji
      JVM_XMS: 128m
      JVM_XMX: 128m
      JVM_MS: 64m
      JVM_MMS: 64m
      MODE: standalone
      NACOS_REPLICAS: 1
      PREFER_HOST_MODE: hostname
    volumes:
      - /home/mydata/nacos/logs:/home/nacos/logs
      - /home/mydata/nacos/data:/home/nacos/data
      - nacos-conf:/home/nacos/conf

  mall-product:
    image: 192.168.1.38:5000/mall-product:0.0.2
    ports:
      - 30003:30003
      - 20882:20882
    container_name: mall-product
    restart: always
    volumes:
      - /home/mydata/mall-product/logs:/log
    environment:
      PROFILES_ACTIVE: test
      DUBBO_IP_TO_REGISTRY: 192.168.1.38
      DUBBO_PORT_TO_BIND: 20882


  mall-order:
    image: 192.168.1.38:5000/mall-order:0.0.4
    ports:
      - 30001:30001
      - 20883:20883
    container_name: mall-order
    restart: always
    volumes:
      - /home/mydata/mall-order/logs:/log
    environment:
      PROFILES_ACTIVE: test
      DUBBO_IP_TO_REGISTRY: 192.168.1.38
      DUBBO_PORT_TO_BIND: 20883


  ride-web:
    image: 192.168.1.38:5000/ride-web:0.0.8
    ports:
      - 20004:20004
    container_name: ride-web
    restart: always
    volumes:
      - /home/mydata/ride-web/logs:/logs
    environment:
      PROFILES_ACTIVE: test


volumes:
  nacos-conf:
    driver: local
    driver_opts:
      type: 'none'
      device: '/home/mydata/nacos/conf'
      o: 'bind'