# 部署graylog

version: '3'

services:

  nginx:
    image: nginx
    restart: always
    privileged: true
    container_name: nginx
    ports:
      - 8080:80
      - 8443:443

    volumes:

      - /home/mydata/nginx/html:/usr/share/nginx/html
      - /home/mydata/nginx/www:/var/www
      - /home/mydata/nginx/logs:/var/log/nginx
      - /home/mydata/nginx/nginx.conf/:/etc/nginx/nginx.conf
      - /home/mydata/nginx/cert:/etc/nginx/cert
      - /home/mydata/nginx/conf.d:/etc/nginx/conf.d

    environment:
      - NGINX_PORT=80
      - TZ=Asia/Shanghai

  mongo:
    image: mongo:4.2
    container_name: mongo
    volumes:
      - /home/mydata/mongo/data:/data/db
    restart: always
    ports:
      - 27017:27017
    networks:
      - graylog

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: es
    volumes:
      - /home/mydata/es/data:/usr/share/elasticsearch/data
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms512m -Xmx512m"

    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - graylog

  graylog:
    image: graylog/graylog:4.2
    container_name: graylog
    volumes:
      - /home/mydata/graylog/data:/usr/share/graylog/data/journal
    environment:
      # 时间
      - GRAYLOG_ROOT_TIMEZONE=Asia/Shanghai
      # 16字符
      - GRAYLOG_PASSWORD_SECRET=tianjigaodaoyuan
      # echo -n "Enter Password: " && head -1 </dev/stdin | tr -d '\n' | sha256sum | cut -d" " -f1
      - GRAYLOG_ROOT_PASSWORD_SHA2=157f69a391ae15eac0d462b50ad789fd61064fcd1b15818ee4e3a02b68d92dab
      # graylog 请求地址
      - GRAYLOG_HTTP_EXTERNAL_URI=http://114.55.66.105:9000/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    networks:
      - graylog
    restart: always
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp


networks:
  graylog:
    driver: bridge