# Generated by Django 4.2 on 2023-07-26 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docker_registry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dockerimagetagsmodel',
            name='repository',
        ),
    ]
