# Generated by Django 4.2 on 2023-07-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_registry', '0002_remove_dockerimagetagsmodel_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockerimagerepositorymodel',
            name='create_user',
            field=models.IntegerField(default=0, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='dockerimagerepositorymodel',
            name='update_user',
            field=models.IntegerField(default=0, null=True, verbose_name='更新人'),
        ),
        migrations.AlterField(
            model_name='dockerimagetagsmodel',
            name='create_user',
            field=models.IntegerField(default=0, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='dockerimagetagsmodel',
            name='update_user',
            field=models.IntegerField(default=0, null=True, verbose_name='更新人'),
        ),
    ]
